### ISSUE TITLE
Make solr endpoint a configurable option rather than hard-coded

### ISSUE THREAD

**Issue by justinccdev** [justinccdev/bsbang-crawler#6]
It's currently hard-coded to the default solr port but really it needs to be user-configurable.

**Comment by innovationchef** [comment]
Currently, the indexed data is stored at http://127.0.0.1:8983/solr/bsbang
By making it user configurable, what do you mean? Could you please cite an example of how you want the output to look like?

**Comment by justinccdev** [comment]
I think for now, adding an optional parameter to the `argparse.ArgumentParser` in `bsbang-index.py` would be enough, one that defaults to http://127.0.0.1:8983/solr/bsbang

**Comment by innovationchef** [comment]
Hey @justinccdev , since the PR is merged, I think we can close this issue.
