### ISSUE TITLE
Setup: add corresponding parameters to the commands for easier setup

### ISSUE THREAD

**Issue by aswanipranjal** [justinccdev/bsbang-crawler#8]
Hey @justinccdev, for setting up the crawler I think that we should also add the parameters that each program file takes, in the **README.md**.

For example:

2. Queue URLs for Bioschemas JSON-LD extraction by adding them directly and crawling sitemaps
```
cd ..
./bsbang-crawl.py <path-to-crawl-db> <location-of-site-map-to-crawl>
```

3. Extract Bioschemas JSON-LD from webpages and insert into the crawl database.
```
./bsbang-extract.py <path-to-crawl-db>
```

6. Run Solr setup
```
cd $BSBANG/setup
./bsbang-setup-solr.py <path-to-bsbang-config-file>
```

7. Index the extracted Bioschemas JSON-LD in Solr
```
cd ..
./bsbang-index.py <path-to-crawl-db>
```
This will make setting it up easier.

**Comment by innovationchef** [comment]
Since the path to db is hardcoded in the setup/bsbang-setup-sqlite.py as `crawl.db` file, I don't see the point of keeping it as the arg. @justinccdev  Is there a purpose for it? 
I found the same issue and edited the readme file - https://github.com/innovationchef/bsbang-crawler/tree/ChangeREADME in my fork.

**Comment by aswanipranjal** [comment]
Hey @innovationchef, I know that the path to DB file is hard coded. But we could have different databases for different sites that we crawl. So I suggested that rather than keeping the same hard-coded value for the DB path we should supply it as a parameter every time we run the file. @justinccdev any thoughts on this?

**Comment by justinccdev** [comment]
@aswanipranjal @innovationchef Yeah, `bsbang-setup-sqlite.py` should really take a crawl db path parameter like the other scripts, rather than be hard-coded.

**Comment by justinccdev** [comment]
@aswanipranjal Yes, the README should be like that, it's currently a bit out of date as that's how it used to be when absolutely everything was hard-coded :).  @innovationchef You've got the right idea with the changes I think, though I would rather the README used placeholders as @aswanipranjal has above.  However, actually examples of invocation are very useful as well, perhaps we could have both.

**Comment by justinccdev** [comment]
Ooops, accidentally closed this issue so re-opened it.
